#!/usr/bin/env bash
#
BASH_COMPAT=4.3   # for SKIP(uses break outside of loops) to work.

bait_show_usage () {
    echo "Usage: ${0##*/} -h or ${0##*/} <testfile> [options] "; cat <<'EOF'
options:
    -n          Don't run tests.
    -P          Don't preprocess the test file.
    -t CASES    A list of comma separated test case numbers to run.
    -T CASES    A list of comma separated test case numbers to skip.
    -i PATTERN  Run only the test cases whose description matches the glob PATTERN.
    -x PATTERN  Skip any test cases whose description matches the glob PATTERN.
    -C          No colors.

# --- FILE: t/example.t --------
 
#!/usr/bin/env bait

test_data1 () { local data=42; }
test_data2 () { local data=69; }

@setup test_data1
@setup test_data2
Case "An Example Test Case Definition" {
    [[ $data -ge 42 ]]
}

Case "Another example with assert checks" {
    assert (( 1 + 1 == 2 ))
    assert "Check if www.google.com is up" {
        local url=https://www.google.com/ 
        [[ $(curl -I -L -sf -w '%{http_code}\n' "$url" | tail -1) == 200 ]]
    }
}
# -----------------------------

# Run it directly
$ chmod +x t/example.t; t/example.t

# Or via prove(1)
$ prove -ve bait t/example.t

EOF
}

bait_die() { echo; echo "Bail out!"; echo "$@" >&2; exit 1; }

bait_main () {
    if [[ $1 = -h ]]; then bait_show_usage; exit 0; fi

    local -; set -e
    local src; src=$(<"${1:?required}"); shift

    local option no_run no_preprocess 
    OPTIND=1
    while getopts ':nPt:T:i:x:Ch' option "$@"; do
        case $option in
            n) no_run=1 ;;
            P) no_preprocess=1 ;;
            t) export BAIT_INCLUDE_TESTS=$OPTARG ;;
            T) export BAIT_EXCLUDE_TESTS=$OPTARG ;;
            i) export BAIT_INCLUDE_PATTERN=$OPTARG ;;
            x) export BAIT_EXCLUDE_PATTERN=$OPTARG ;;
            C) export BAIT_NO_COLORS=1 ;;
            h) bait_show_usage; exit ;;
            -) break ;;
            :) bait_die "Missing option argument for -$OPTARG" ;;
            \?) bait_die "Unknown option: -$OPTARG" ;;
        esac
    done
    shift $((OPTIND - 1))
    (( $# == 0 )) || { bait_show_usage; exit 1; }


    if [[ ! ${no_preprocess:-} ]]; then
        src=$(_preprocess <<<"$src")
    fi
    if [[ ! ${no_run:-} ]]; then
        exec "$BASH" <(
            printf "source %q; %s\n" "$0" "$src"
            echo "set +e; bait_run_tests"
        )
    else
        printf "%s\n" "$src"
    fi
}



ESC=$'\e'
C_RED=$ESC[31m
C_GREEN=$ESC[32m
C_CYAN=$ESC[36m
C_YELLOW=$ESC[33m
C_OFF=$ESC[39m

OK=ok
NOT_OK='not ok'

CASES=()        # A temporary stack for storing test case name.

# test case functinon name --> case description
declare -gA CASE_DESCRIPTIONS

CASE_STATE=;    # SKIP or TODO.
STATE_REASON=;  # reason for the above state.

TESTS=()        # A list of test case function names accumulated so far.
                # These are candidates for bait_run_tests().

EXIT_CMDS=()    # a list commands to run at script end.

trap 'for cmd in "${EXIT_CMDS[@]}"; do $cmd; done' EXIT

# Accumulate each `@setup` call's arguments for the current defining
# test case.
SETUPS=()       # ("setup_func1 setup_func2 ..." ...)

# test case function name --> a string of space separated list of
# setup function names.
declare -gA TEST_SETUPS

TEST_STATUS=0   # The last test run status; 0 means OK.

# Temporary directory to capture test output; initialized before running tests.
TEST_OUTPUT_DIR=



# Usage: `Case` `[description]`
#
# Mark the beginning of a test case, optionally with a case description.
# This command should be followed immediately with a `Do()` function
# definition, which should be followed immediately with an `End` command.
#
# Example:
#
#     Case "test case description..."; Do () {
#         ...asserts and checks go here...
#     }
#     End Case
#
# Here the `Do()` provides the actual test case function definition,
# inside which you can run your checks. The status(i.e., 0 or 1) of a test
# case is the return status of its `Do` function call OR(`||`, i.e., the
# logical OR) together with the status of all `check` calls in it.
#
Case () {
    if [[ ${#CASES[*]} != 0 ]]; then
        bait_die "ERROR: Nested test cases not supported."
    fi
    if [[ ${*:-} == *#* ]]; then
        bait_die "ERROR: Sorry, '#' is not allowed in test case descriptions."
    fi
    CASES+=("$*")
}

# Usage: `End Case`
#
# Mark the end of a test case definition.
# This command should be run immediately after a `Do()` definition.
#
# The first argument is reserved, and currently can only be `Case`.
# The rest of arguments can be anything and will be ignored.
#
# See `Case()` above.
#
End () {
    if [[ ${#CASES[*]} -eq 0 ]]; then
        bait_die "ERROR: No matching 'Case' command!"
    fi
    if (( ! ${#SETUPS[*]} )); then
        SETUPS+=("")
    fi

    local fbody; fbody=$(declare -f Do | sed 1d)
    [[ ${fbody:-} ]] || bait_die "ERROR: No matching 'Do' definition!"
    unset -f Do

    local desc=${CASES[-1]}; unset 'CASES[-1]'

    local setup_funcs funcname
    for setup_funcs in "${SETUPS[@]}"; do
        funcname=Test_$(( ${#TESTS[*]} + 1 ))
        eval "$funcname () $fbody"

        CASE_DESCRIPTIONS[$funcname]=$desc
        if [[ ${setup_funcs:-} ]]; then
            TEST_SETUPS[$funcname]=$setup_funcs
        fi
        TESTS+=($funcname)
    done
    SETUPS=()
}

# Check the last assert definition and set the status of the
# current test case.
#
# This command is usually invoked immediately after an `assert()`
# definition.
#
# Example:
#
#     assert () { (( 1 + 1 == 2 )); }; check
#
check () {
    local out=$TEST_OUTPUT_DIR/${FUNCNAME[1]}.asserts stderr
    local return_code color

    exec {stderr}>&2 2>>$out
    echo "$(declare -f assert)" >&2

    if [[ $BAIT_NO_COLORS ]]; then color=''; else color=$C_RED; fi
    echo "$color" >&2
    set -x
    assert; return_code=$?
    set +x
    if [[ $BAIT_NO_COLORS ]]; then color=''; else color=$C_OFF; fi
    echo "$color" >&2

    eval exec "2>&$stderr $stderr>&-"

    TEST_STATUS=$(($TEST_STATUS || $return_code))
}

# Test result directives. These should only be used at
# the test case level.
#

# Usage 1: SKIP [reason]
# Usage 2: SKIP <levels>
# Usage 3: SKIP <reason> <levels>
#
# If used inside a loop, then you must specify the correct `level`,
# which is the number of enclosing loops in the call chain up to the
# enclosing test case function, to skip. 
#
# If `0` is specified for `level` then `SKIP` will mark the test case
# as skipped and then return to the test case. It is then up to you
# to decide whether to `return` or continue the test case.
#
# The following examples all skip the containing test cases:
#
#     Case; Do () { SKIP; }; End Case
#     Case; Do () { SKIP "reason..."; }; End Case
#     Case; Do () { while true; do SKIP 1; done; }; End Case
#     Case; Do () { while true; do SKIP "reason..." 1; done; }; End Case
#     Case; Do () { while true; do while true; do SKIP "reason..." 2; done; done; }; End Case
#     Case; Do () { while true; do while true; do SKIP 0; return; done; done; }; End Case
#     Case; Do () { while true; do while true; do SKIP "reason..." 0; return; done; done; }; End Case
#
SKIP () {
    local -; set +x
    CASE_STATE=SKIP
    if [[ ${!#} =~ ^[1-9][0-9]*$ ]]; then
        STATE_REASON=${@:1:$#-1}
        break $(( ${!#} + 1 ))

    elif [[ ${!#} != 0 ]]; then
        STATE_REASON=$*
        break
    fi
    # i.e., we have: SKIP [...] 0
    STATE_REASON=${@:1:$#-1}
}

# Mark the test case as todo, and as such, this test
# result won't count towards the final results.
#
TODO () {
    CASE_STATE=TODO; STATE_REASON=$*
}


# Specify a list of setup functions for its following test case.
#
# A setup function can be any function. It is used to set up the
# test fixture(i.e., test data or whatever needed for its tests),
# and when the test case is run, such setup function will call
# the actuall test case function, and therefore giving it access
# to all its local variables via dynamic scoping.
#
# Example:
#
#     @setup A B C
#     Case MyTest; Do () { ...; }; End Case
#
# To run the `MyTest` case, we'll run `A()`, which will call `B()` at the
# end, which will call `C()` at the end, which will call `MyTest`'s 
# test function at the end.
#
# In rare cases, you might want/need to specify where in a setup
# function the next setup function is called. This can be accomplished
# by the `: __HOLE__` null command. If specified, the line that starts
# with such null command will be replaced by the call to the next setup
# function.
#
# It's also possible to have multiple `@setup` for a test case.
# For example:
#
#     @setup A B
#     @setup A C
#     Case MyTest; Do () { ...; }; End Case
#
# This will actually create two test cases, with the same test case
# function, with different setups; one for `@setup A B` and the other
# for `@setup A C`. This way, you can easily prepare different fixtures
# to run your test case.
#
@setup () { SETUPS+=("$*"); }


# Run the test cases, producing TAP style outputs.
#
bait_run_tests () {
    TEST_OUTPUT_DIR=$(mktemp -d tmp.XXXXXXXXXXXX) && 
        EXIT_CMDS+=("rm -rf $(printf "%q\n" "$TEST_OUTPUT_DIR")") \
        || bait_die "Failed creating need temporary directory!"

    local test_func test_num case_desc target failed_tests=()

    __set_case_desc () {
        case_desc=${CASE_DESCRIPTIONS[$test_func]}
        case_desc=${case_desc:+ - $case_desc}
    }
    __skip_test_func () {
        once=; CASE_STATE=SKIP
        STATE_REASON="user directed skip at CLI"
    }

    echo 1..${#TESTS[*]}

    for test_func in "${TESTS[@]}"; do
        test_num=${test_func##*_}
        __set_case_desc

        local setups=(${TEST_SETUPS[$test_func]:-})
        if (( ${#setups[*]} )); then
            _hook_up ${setups[*]} $test_func
            target=${setups%% *}_hooked
        else
            target=$test_func
        fi

        local only once=1
        CASE_STATE=; STATE_REASON=; TEST_STATUS=0; 

        [[ ${BAIT_INCLUDE_TESTS:-} ]] && {
            [[ ,$BAIT_INCLUDE_TESTS, == *,$test_num,* ]] || __skip_test_func
        }
        [[ ${BAIT_EXCLUDE_TESTS:-} ]] && {
            [[ ,$BAIT_EXCLUDE_TESTS, != *,$test_num,* ]] || __skip_test_func
        }
        [[ ${BAIT_INCLUDE_PATTERN:-} ]] && {
            [[ $case_desc == $BAIT_INCLUDE_PATTERN ]]    || __skip_test_func
        }
        [[ ${BAIT_EXCLUDE_PATTERN:-} ]] && {
            [[ $case_desc != $BAIT_EXCLUDE_PATTERN ]]    || __skip_test_func
        }

        for only in $once; do  # for SKIP to break out of.
            local stdout=$TEST_OUTPUT_DIR/$test_func.out
            local stderr=$TEST_OUTPUT_DIR/$test_func.err
            $target >"$stdout" 2>"$stderr"
            TEST_STATUS=$(($TEST_STATUS || $?))
        done

        if [[ $TEST_STATUS -ne 0 ]]; then
            failed_tests+=($test_func)
        fi

        local directive=${CASE_STATE:+" # $CASE_STATE${STATE_REASON:+" $STATE_REASON"}"}
        echo "${OK[$TEST_STATUS]:-$NOT_OK} $test_num$case_desc$directive"
        echo

        local setup_func
        while (( ${#setups[*]} )); do
            setup_func=${setups[-1]}
            if declare -F ${setup_func}_teardown >/dev/null; then
                ${setup_func}_teardown 
            fi
            unset -f ${setup_func}_hooked
            unset 'setups[-1]'
        done
    done

    local c_off
    for test_func in  "${failed_tests[@]}"; do
        __set_case_desc
        echo
        echo =========================================
        echo "Failed $test_func$case_desc"
        echo "--- Failed asserts ---------------------"
        if [[ -e "$TEST_OUTPUT_DIR/$test_func.asserts" ]]; then
            if [[ $BAIT_NO_COLORS ]]; then c_off=''; else c_off=$C_OFF; fi
            awk -v C_OFF=$c_off '
                 /^assert \(\)/,/^\+ return_code=[0-9]+/ { lines[i++]=$0     }
                 /^\+ return_code=0/                     { delete lines; i=0 }
                 /^\+ return_code=[^0]/                  { for (j=0; j < i; j++) print lines[j]
                                                           print C_OFF
                                                           delete lines; i=0
                                                         }
                ' < "$TEST_OUTPUT_DIR/$test_func.asserts"
        fi
        echo "--- Captured stdout --------------------"
        cat "$TEST_OUTPUT_DIR/$test_func.out"
        echo "--- Captured stderr --------------------"
        cat "$TEST_OUTPUT_DIR/$test_func.err"
        echo "----------------------------------------"
    done >&2
}



_hook_up () {
    local funcs src1 chain=()
    local opts=$- oIFS=$IFS

    # e.g., funcs=(test_func setup_func3 setup_func2   setup_func1)
    #              ^^^^^^^^^             ^^^^^^^^^^^   ^^^^^^^^^^^
    #                last                $second       $first
    local i=$(($# + 1)) funcs=()
    while (( --i )); do funcs+=(${!i}); done

    while (( ${#funcs[*]} > 1 )); do

        # take the last two items off the funcs
        local first=${funcs[-1]}; second=${funcs[-2]}; unset 'funcs[-1]'

        # get the source code for the function to be hooked
        src1=$(declare -f $first | sed "1s/^$first/${first}_hooked/"; exit $PIPESTATUS) || return $?

        # if there's a __HOLE__ marker indicating where we call $second in $first
        if [[ $src1 =~ $'\n'\ *:\ +__HOLE__ ]]; then
            src1=$(sed "s/^ *:  *__HOLE__/$second/" <<<"$src1")
        else
            # just call $second as the last command in $first

            set -f; IFS=$'\n'
            local lines=($src1)
            local last=${lines[-1]}

            # if this isn't the last iteration
            if [[ ${#funcs[*]} -gt 1 ]]; then
                lines[${#lines[*]} - 1]=${second}_hooked
            else
                lines[${#lines[*]} - 1]=$second  # this is the test_func
            fi
            lines+=("$last")
            src1=${lines[*]}
            IFS=$oIFS; set +f; set -$opts
        fi
        chain+=("$src1")
   done

   IFS=$'\n'; eval "${chain[*]}"; IFS=$oIFS
}


_preprocess () {
    sed -re "
        s/^(\s*Case(\s+.*)?)\s(\{|\()/\1; Do () \3/

        s/^(\s*assert)\s+(.*[^;{])\s*$/\1 () { \2; }; check/

        s/^(\s*assert)\s+(.*)\s*\{\s*$/\1 () { : \2/
    " | (
        declare -gA brackets=([\{]=\} [\(]=\)); NL=$'\n' IFS=$NL
        while read -r line; do
            if [[ ${found_assert:-} && ${line:-} == "${assert_indent:-}}"* ]]; then
                line="${assert_indent:-}}${NL}${assert_indent:-}check"
                found_assert=

            elif [[ ${end_char:-} && ${line:-} == "$indent$end_char"* ]]; then
                line="${indent:-}$end_char${NL}${indent:-}End Case"
                end_char=
            
            # single line: Case ...; Do () { .... }
            elif [[ ${line:-} =~ ^([[:space:]]*)Case([[:space:]]+|\;).+(\)|\})[[:space:]]*$ ]]; then
                line="$line; End Case"

            # multi-line Case block
            elif [[ ${line:-} =~ ^([[:space:]]*)Case([[:space:]]+|\;).+(\{|\()[[:space:]]*$ ]]; then
                indent=${BASH_REMATCH[1]}
                end_char=${brackets[${BASH_REMATCH[3]}]}

            # multi-line assert block
            elif [[ ${line:-} =~ ^([[:space:]]*)assert([[:space:]]+|\().+\{\ :.*$ ]]; then
                found_assert=1
                assert_indent=${BASH_REMATCH[1]}
            fi
            echo "${line:-}"
        done
    )
}

if [[ $BASH_SOURCE == "$0" ]]; then
    bait_main "$@"
fi
